// Vehicle images hosted locally in public/vehicles/
// Map: `${makeSlug}/${modelSlug}` → local path

const IMAGES: Record<string, string> = {
  "acura/mdx": "/vehicles/acura-mdx.jpg",
  "acura/rdx": "/vehicles/acura-rdx.jpg",
  "audi/a3": "/vehicles/audi-a3.jpg",
  "audi/a4": "/vehicles/audi-a4.jpg",
  "audi/q5": "/vehicles/audi-q5.jpg",
  "bmw/3-series": "/vehicles/bmw-3-series.jpg",
  "bmw/x5": "/vehicles/bmw-x5.jpg",
  "cadillac/escalade": "/vehicles/cadillac-escalade.jpg",
  "chevrolet/equinox": "/vehicles/chevrolet-equinox.jpg",
  "chevrolet/malibu": "/vehicles/chevrolet-malibu.jpg",
  "chevrolet/silverado-1500": "/vehicles/chevrolet-silverado-1500.jpg",
  "chevrolet/tahoe": "/vehicles/chevrolet-tahoe.jpg",
  "chrysler/pacifica": "/vehicles/chrysler-pacifica.jpg",
  "dodge/charger": "/vehicles/dodge-charger.jpg",
  "ford/bronco": "/vehicles/ford-bronco.jpg",
  "ford/escape": "/vehicles/ford-escape.jpg",
  "ford/explorer": "/vehicles/ford-explorer.jpg",
  "ford/f-150": "/vehicles/ford-f-150.jpg",
  "ford/maverick": "/vehicles/ford-maverick.jpg",
  "ford/mustang": "/vehicles/ford-mustang.jpg",
  "gmc/sierra-1500": "/vehicles/gmc-sierra-1500.jpg",
  "honda/accord": "/vehicles/honda-accord.jpg",
  "honda/civic": "/vehicles/honda-civic.jpg",
  "honda/cr-v": "/vehicles/honda-cr-v.jpg",
  "honda/odyssey": "/vehicles/honda-odyssey.jpg",
  "honda/pilot": "/vehicles/honda-pilot.jpg",
  "hyundai/elantra": "/vehicles/hyundai-elantra.jpg",
  "hyundai/palisade": "/vehicles/hyundai-palisade.jpg",
  "hyundai/santa-fe": "/vehicles/hyundai-santa-fe.jpg",
  "hyundai/sonata": "/vehicles/hyundai-sonata.jpg",
  "hyundai/tucson": "/vehicles/hyundai-tucson.jpg",
  "jeep/grand-cherokee": "/vehicles/jeep-grand-cherokee.jpg",
  "jeep/wrangler": "/vehicles/jeep-wrangler.jpg",
  "kia/sorento": "/vehicles/kia-sorento.jpg",
  "kia/sportage": "/vehicles/kia-sportage.jpg",
  "kia/telluride": "/vehicles/kia-telluride.jpg",
  "lexus/es": "/vehicles/lexus-es.jpg",
  "lexus/nx": "/vehicles/lexus-nx.jpg",
  "lexus/rx": "/vehicles/lexus-rx.jpg",
  "mazda/cx-5": "/vehicles/mazda-cx-5.jpg",
  "mazda/cx-50": "/vehicles/mazda-cx-50.jpg",
  "mazda/mazda3": "/vehicles/mazda-mazda3.jpg",
  "mercedes-benz/c-class": "/vehicles/mercedes-benz-c-class.jpg",
  "mercedes-benz/e-class": "/vehicles/mercedes-benz-e-class.jpg",
  "mercedes-benz/glc": "/vehicles/mercedes-benz-glc.jpg",
  "nissan/altima": "/vehicles/nissan-altima.jpg",
  "nissan/pathfinder": "/vehicles/nissan-pathfinder.jpg",
  "nissan/rogue": "/vehicles/nissan-rogue.jpg",
  "nissan/sentra": "/vehicles/nissan-sentra.jpg",
  "porsche/911": "/vehicles/porsche-911.jpg",
  "porsche/cayenne": "/vehicles/porsche-cayenne.jpg",
  "porsche/macan": "/vehicles/porsche-macan.jpg",
  "ram/1500": "/vehicles/ram-1500.jpg",
  "subaru/ascent": "/vehicles/subaru-ascent.jpg",
  "subaru/crosstrek": "/vehicles/subaru-crosstrek.jpg",
  "subaru/forester": "/vehicles/subaru-forester.jpg",
  "subaru/outback": "/vehicles/subaru-outback.jpg",
  "tesla/model-3": "/vehicles/tesla-model-3.jpg",
  "tesla/model-y": "/vehicles/tesla-model-y.jpg",
  "toyota/4runner": "/vehicles/toyota-4runner.jpg",
  "toyota/camry": "/vehicles/toyota-camry.jpg",
  "toyota/corolla": "/vehicles/toyota-corolla.jpg",
  "toyota/highlander": "/vehicles/toyota-highlander.jpg",
  "toyota/rav4": "/vehicles/toyota-rav4.jpg",
  "toyota/sienna": "/vehicles/toyota-sienna.jpg",
  "toyota/tacoma": "/vehicles/toyota-tacoma.jpg",
  "toyota/tundra": "/vehicles/toyota-tundra.jpg",
  "volkswagen/atlas": "/vehicles/volkswagen-atlas.jpg",
  "volkswagen/golf-gti": "/vehicles/volkswagen-golf-gti.jpg",
  "volkswagen/jetta": "/vehicles/volkswagen-jetta.jpg",
  "volkswagen/tiguan": "/vehicles/volkswagen-tiguan.jpg",
  "volvo/xc60": "/vehicles/volvo-xc60.jpg",
  "volvo/xc90": "/vehicles/volvo-xc90.jpg",
};

export function getVehicleImageUrl(makeSlug: string, modelSlug: string): string | null {
  return IMAGES[`${makeSlug}/${modelSlug}`] ?? null;
}
