export type WarningLightSeverity = "critical" | "caution" | "informational";

export interface WarningLight {
  slug: string;
  title: string;
  severity: WarningLightSeverity;
  meaning: string;
  causes: string[];
  can_drive: string;
  min_cost: number;
  max_cost: number;
  icon: string; // SVG path data or inline SVG
  related_obd_codes: string[];
}

// Standard ISO 2575 dashboard symbols as inline SVG
const ICONS: Record<string, string> = {
  checkEngine: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><rect x="6" y="10" width="52" height="34" rx="4" stroke="currentColor" stroke-width="3"/><path d="M24 44v6h16v-6" stroke="currentColor" stroke-width="3"/><path d="M28 10V4h8v6" stroke="currentColor" stroke-width="3"/><path d="M32 24v12" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="20" r="2.5" fill="currentColor"/></svg>`,
  oilPressure: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><path d="M26 6h12l3 8h10a3 3 0 013 3v32a3 3 0 01-3 3H13a3 3 0 01-3-3V17a3 3 0 013-3h10l3-8z" stroke="currentColor" stroke-width="3"/><path d="M24 36l4-4 6 6 8-8" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  battery: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><rect x="10" y="16" width="36" height="32" rx="4" stroke="currentColor" stroke-width="3"/><path d="M46 22h4a3 3 0 013 3v14a3 3 0 01-3 3h-4" stroke="currentColor" stroke-width="3"/><path d="M18 28v8M26 28v8M34 28v8" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,
  brake: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="32" r="22" stroke="currentColor" stroke-width="3"/><path d="M32 18v16" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="44" r="3" fill="currentColor"/></svg>`,
  coolantTemp: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><path d="M28 8v32" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><rect x="20" y="8" width="16" height="3" rx="1.5"/><path d="M20 50a8 8 0 108.5-7.8" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,
  tpms: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="38" r="16" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="38" r="7" stroke="currentColor" stroke-width="3"/><rect x="26" y="4" width="12" height="12" rx="2" stroke="currentColor" stroke-width="3"/><path d="M32 16v10" stroke="currentColor" stroke-width="3"/></svg>`,
  abs: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="32" r="22" stroke="currentColor" stroke-width="3"/><text x="32" y="40" text-anchor="middle" font-size="20" font-weight="900" fill="currentColor" stroke="none" font-family="sans-serif">ABS</text></svg>`,
  airbag: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="26" r="9" stroke="currentColor" stroke-width="3"/><path d="M24 50l8-10 8 10" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="36" r="14" stroke="currentColor" stroke-width="2" stroke-dasharray="4 2"/></svg>`,
  traction: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><path d="M14 26h36M14 38h36" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><path d="M18 16l-8 10 8 10" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  powerSteering: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="32" r="18" stroke="currentColor" stroke-width="3"/><circle cx="32" cy="32" r="4" stroke="currentColor" stroke-width="3"/><path d="M32 14v6M32 44v6M14 32h6M44 32h6" stroke="currentColor" stroke-width="3"/></svg>`,
  oilChange: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><path d="M20 8h8l2 4h6a2 2 0 012 2v20a2 2 0 01-2 2H12a2 2 0 01-2-2V14a2 2 0 012-2h6l2-4z"/><path d="M14 26v-2h20v2"/><circle cx="14" cy="28" r="1.5" fill="currentColor" stroke="none"/></svg>`,
  glowPlug: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><path d="M30 6c0 0-2 10-2 18 0 5 2 8 4 8s4-3 4-8c0-8-2-18-2-18" stroke="currentColor" stroke-width="3"/><path d="M22 40l10-6 10 6" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>`,
  esc: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><path d="M8 24h32M8 34h32"/><path d="M14 14l-6 10 6 10"/><circle cx="28" cy="14" r="6"/><path d="M30 10l4-4"/></svg>`,
  security: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><rect x="12" y="28" width="18" height="22" rx="3" stroke="currentColor" stroke-width="3"/><path d="M18 28v-8a6 6 0 0112 0v8" stroke="currentColor" stroke-width="3"/><circle cx="21" cy="41" r="2.5" fill="currentColor"/></svg>`,
  fuel: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><rect x="10" y="12" width="24" height="40" rx="4" stroke="currentColor" stroke-width="3"/><path d="M34 24h10a3 3 0 013 3v12a4 4 0 01-4 4" stroke="currentColor" stroke-width="3"/></svg>`,
  seatbelt: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><circle cx="24" cy="16" r="4"/><path d="M24 20v18"/><path d="M18 24l6-4 6 4"/></svg>`,
  door: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><rect x="6" y="6" width="36" height="36" rx="3"/><rect x="28" y="8" width="12" height="28" rx="1"/><circle cx="34" cy="24" r="1.5" fill="currentColor" stroke="none"/></svg>`,
  reducedPower: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><path d="M32 10l-12 24h10l-6 20 18-24h-10l6-20z" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/></svg>`,
  washerFluid: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><rect x="12" y="8" width="24" height="32" rx="3"/><path d="M18 18h12M18 24h12M20 30h2"/><path d="M24 6l3-3 3 3"/></svg>`,
  service: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><rect x="8" y="10" width="32" height="20" rx="3"/><path d="M16 30v4h16v-4"/><path d="M20 10V6h8v4"/><circle cx="24" cy="22" r="1.5" fill="currentColor" stroke="none"/><path d="M18 24l6-4 6 4"/></svg>`,
  adBlue: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><rect x="8" y="14" width="20" height="20" rx="3"/><path d="M28 22h6a2 2 0 012 2v4"/><path d="M16 22v4M22 22v4"/></svg>`,
  dpf: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><rect x="6" y="18" width="36" height="12" rx="2"/><path d="M6 22h4M38 22h4"/><circle cx="18" cy="24" r="3"/><circle cx="30" cy="24" r="3"/></svg>`,
  ev: `<svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" height={48}><path d="M24 8l-6 18h8l-4 14 10-18h-8l6-14z"/></svg>`,
  generic: `<svg viewBox="0 0 64 64" fill="none" width={64} height={64}><circle cx="32" cy="32" r="22" stroke="currentColor" stroke-width="3"/><path d="M32 18v16" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="46" r="3" fill="currentColor"/></svg>`,
};

export const warningLights: WarningLight[] = [
  {
    slug: "check-engine",
    title: "Check Engine Light (MIL)",
    severity: "caution",
    meaning: "The Malfunction Indicator Lamp means your vehicle's ECU has detected a fault in the engine, emissions, or fuel system. This is the most common warning light, covering everything from a loose gas cap to a failed catalytic converter.",
    causes: [
      "Loose or damaged gas cap (most common — tighten first)",
      "Faulty oxygen sensor (upstream or downstream)",
      "Worn spark plugs or ignition coils",
      "Failing catalytic converter (often secondary to other issues)",
      "Mass airflow (MAF) sensor failure",
      "EVAP system leak (small or large)",
      "EGR valve stuck open or closed",
    ],
    can_drive: "Steady light: usually safe to drive short distances, but diagnose soon. Flashing light: STOP immediately — active engine misfire can destroy the catalytic converter within minutes. Tow to a shop if flashing.",
    min_cost: 0, max_cost: 3000, icon: ICONS.checkEngine,
    related_obd_codes: ["P0420", "P0300", "P0171", "P0455", "P0442", "P0401", "P0101", "P0301", "P0302", "P0303"],
  },
  {
    slug: "oil-pressure",
    title: "Oil Pressure Warning",
    severity: "critical",
    meaning: "Engine oil pressure has dropped below safe levels. This can mean low oil level, a failing oil pump, a clogged oil pickup screen, or worn engine bearings. Running an engine without oil pressure causes catastrophic damage in seconds to minutes.",
    causes: [
      "Low engine oil level (check dipstick immediately)",
      "Oil pump failure",
      "Clogged oil pickup screen or filter",
      "Worn main or rod bearings (internal engine damage)",
      "Faulty oil pressure sensor",
      "Oil dilution from leaking fuel injectors",
    ],
    can_drive: "DO NOT drive. Stop the engine immediately as soon as it is safe to pull over. Check oil level. If oil level is normal, the issue is likely the pump or sensor — tow to a shop. Driving even a few blocks with no oil pressure can seize the engine.",
    min_cost: 0, max_cost: 8000, icon: ICONS.oilPressure,
    related_obd_codes: ["P0520", "P0521", "P0522", "P0523", "P06DA", "P06DB"],
  },
  {
    slug: "battery-charging",
    title: "Battery / Charging System Warning",
    severity: "critical",
    meaning: "The alternator is not charging the battery. Your vehicle is running on battery power alone, and once the battery drains, the engine will stall and all electrical systems will shut down. This is NOT a battery problem — it's a charging system problem.",
    causes: [
      "Faulty alternator (most common)",
      "Broken or slipping serpentine belt",
      "Corroded or loose battery terminals",
      "Bad voltage regulator",
      "Blown alternator fuse or fusible link",
      "Wiring harness damage",
    ],
    can_drive: "Briefly — you have 15-45 minutes of battery power remaining. Turn off all unnecessary electrical loads (AC, radio, heated seats). Drive directly to a shop or a safe location. Do not attempt long-distance driving.",
    min_cost: 100, max_cost: 800, icon: ICONS.battery,
    related_obd_codes: ["P0562", "P0563", "P0620", "P0622", "P2502", "P2503"],
  },
  {
    slug: "brake-system",
    title: "Brake System Warning",
    severity: "critical",
    meaning: "Can indicate engaged parking brake, low brake fluid level, a fault in the ABS system, or a serious hydraulic failure. In some vehicles, this light also serves as the parking brake indicator.",
    causes: [
      "Parking brake is partially engaged (check first)",
      "Low brake fluid (may indicate worn brake pads or a leak)",
      "Brake fluid leak in master cylinder, calipers, or lines",
      "Failed ABS pump or module",
      "Worn brake pads below minimum thickness",
      "Brake pad wear sensor triggered",
    ],
    can_drive: "If the parking brake is disengaged and fluid level is normal: test brake pedal feel at low speed. If pedal is firm, drive cautiously to a shop. If pedal is soft, sinks to floor, or vehicle pulls — STOP and tow. Brake failure is not survivable at speed.",
    min_cost: 80, max_cost: 2000, icon: ICONS.brake,
    related_obd_codes: ["C0265", "C0267", "C0271", "C0273", "C1210", "C1221"],
  },
  {
    slug: "coolant-temperature",
    title: "Engine Coolant Temperature Warning",
    severity: "critical",
    meaning: "Engine coolant temperature has exceeded safe operating range. Overheating can warp cylinder heads, blow head gaskets, and cause permanent engine damage. This light may be red (overheating) or blue (engine cold — normal on startup).",
    causes: [
      "Low coolant level (check reservoir when engine is COLD)",
      "Coolant leak (radiator, hoses, water pump, head gasket)",
      "Failed thermostat (stuck closed)",
      "Failed water pump",
      "Clogged radiator (internal or external)",
      "Cooling fan not operating",
      "Blown head gasket (combustion gases entering coolant)",
    ],
    can_drive: "Red light: pull over and shut off the engine immediately. Wait at least 30 minutes before checking coolant — opening a hot radiator cap will cause severe burns. If coolant is full and engine was not severely overheated, drive short distances to a shop. If steam or coolant is visible, tow.",
    min_cost: 50, max_cost: 3500, icon: ICONS.coolantTemp,
    related_obd_codes: ["P0115", "P0117", "P0118", "P0128", "P0217", "P2181"],
  },
  {
    slug: "tpms",
    title: "Tire Pressure Monitoring System (TPMS)",
    severity: "caution",
    meaning: "One or more tires has low pressure (solid light) or the TPMS system itself has a fault (flashing light). Underinflated tires reduce fuel economy, increase stopping distance, and can cause blowouts at highway speeds.",
    causes: [
      "Low tire pressure (most common — check and inflate to door placard spec)",
      "Seasonal temperature drop (pressure drops ~1 PSI per 10°F)",
      "Slow leak from nail or puncture",
      "Dead TPMS sensor battery (sensors last 5-10 years)",
      "Faulty TPMS receiver module",
      "Tire rotation without TPMS relearn procedure",
    ],
    can_drive: "Yes, but check and inflate tires as soon as possible. If the light flashes then stays solid, a TPMS sensor has failed — safe to drive but the system cannot warn you of low pressure. Get sensors replaced at your next tire service.",
    min_cost: 0, max_cost: 400, icon: ICONS.tpms,
    related_obd_codes: ["C0750", "C0755", "C0760", "C0765", "C0775"],
  },
  {
    slug: "abs",
    title: "Anti-lock Braking System (ABS) Warning",
    severity: "caution",
    meaning: "The ABS system has detected a fault and is disabled. Your regular brakes still work, but the anti-lock function (which prevents wheel lockup during emergency braking) is not available. The vehicle may also disable traction control and stability control when ABS fails.",
    causes: [
      "Faulty wheel speed sensor (most common)",
      "Damaged ABS tone ring (rusted or cracked)",
      "ABS module internal fault",
      "Blown ABS fuse",
      "Low brake fluid (shared reservoir on some vehicles)",
      "Wiring damage at wheel sensor connector",
    ],
    can_drive: "Yes — normal braking still works. Drive cautiously, especially in wet or icy conditions where ABS is most needed. The vehicle will pass mechanical safety inspections but fail electronic brake system checks.",
    min_cost: 100, max_cost: 1500, icon: ICONS.abs,
    related_obd_codes: ["C0035", "C0040", "C0045", "C0050", "C1221", "C1225"],
  },
  {
    slug: "airbag",
    title: "Supplemental Restraint System (SRS / Airbag)",
    severity: "caution",
    meaning: "The airbag system has a fault. In a collision, one or more airbags may not deploy, or may deploy unexpectedly. This is a passive safety system — the vehicle drives normally, but occupant protection is compromised.",
    causes: [
      "Faulty clock spring in steering wheel (most common)",
      "Loose connector under driver or passenger seat",
      "Faulty side impact sensor",
      "Damaged seat belt pre-tensioner",
      "Airbag module internal fault",
      "Previous deployment not reset (salvage vehicles)",
    ],
    can_drive: "Yes — but airbags may not deploy in a crash. Passengers should be aware. Common cause is debris under the seat disconnecting the yellow SRS connector — check under seats first.",
    min_cost: 50, max_cost: 1500, icon: ICONS.airbag,
    related_obd_codes: ["B0001", "B0002", "B0010", "B0011", "B0020", "B0090"],
  },
  {
    slug: "traction-control",
    title: "Traction Control / Stability Control (TCS/ESC)",
    severity: "caution",
    meaning: "The traction control or electronic stability control system has been disabled, either by a switch or due to a fault. These systems help prevent wheel spin and loss of control. The light may flash during active intervention (normal) or stay solid (fault).",
    causes: [
      "System manually turned off (check TC/ESC button)",
      "Faulty wheel speed sensor (shared with ABS system)",
      "Steering angle sensor needs recalibration",
      "ABS module fault (TCS/ESC depends on ABS sensors)",
      "Low battery voltage causing module error",
      "Yaw rate sensor fault",
    ],
    can_drive: "Yes — but be more cautious on wet, icy, or loose surfaces. The vehicle will not prevent wheel spin or skidding. If the light stays on after restarting the vehicle, have it scanned.",
    min_cost: 50, max_cost: 1200, icon: ICONS.traction,
    related_obd_codes: ["C0035", "C0040", "C0050", "C1233", "C1288", "U0121"],
  },
  {
    slug: "power-steering",
    title: "Electric Power Steering (EPS) Warning",
    severity: "caution",
    meaning: "The electric power steering system has a fault. Steering effort will increase significantly, especially at low speeds and during parking maneuvers. Hydraulic power steering uses a different warning (see Power Steering Fluid).",
    causes: [
      "EPS motor or torque sensor failure",
      "Low battery voltage or charging system issue",
      "Steering angle sensor out of calibration",
      "EPS control module fault",
      "Blown EPS fuse",
      "Software glitch (often resolved by restarting the vehicle)",
    ],
    can_drive: "Yes — but steering will be noticeably heavier, especially during parking. Avoid tight maneuvers. If steering becomes extremely difficult or locks, pull over safely. Many EPS faults reset after turning the vehicle off and restarting.",
    min_cost: 200, max_cost: 2500, icon: ICONS.powerSteering,
    related_obd_codes: ["C0541", "C0545", "C0550", "U0131", "U0415"],
  },
  {
    slug: "glow-plug",
    title: "Glow Plug Indicator (Diesel)",
    severity: "informational",
    meaning: "This light has two functions on diesel engines: 1) Preheating: light is on while glow plugs warm up before starting (normal, wait until it goes out before cranking). 2) Fault: light stays on or flashes while driving — indicates a glow plug, glow plug relay, or engine management fault.",
    causes: [
      "Glow plug failure (individual plugs wear out over time)",
      "Glow plug relay / control module failure",
      "Engine management fault (flashing light)",
      "Wiring harness damage near glow plugs",
      "Cold start injector fault (older diesels)",
    ],
    can_drive: "Yes — the light during preheating is normal. If it stays on or flashes while driving, the vehicle is still driveable but may be harder to start cold and may have reduced power or increased emissions. Diagnose at next service.",
    min_cost: 80, max_cost: 600, icon: ICONS.glowPlug,
    related_obd_codes: ["P0380", "P0381", "P0382", "P0670", "P0671", "P0672"],
  },
  {
    slug: "reduced-power",
    title: "Reduced Engine Power / Limp Mode",
    severity: "critical",
    meaning: "The engine ECU has detected a serious fault and has limited engine output to protect the engine, transmission, or emissions system. The vehicle may have severely reduced acceleration and limited top speed. This is sometimes called 'limp home mode.'",
    causes: [
      "Throttle body or accelerator pedal position sensor fault",
      "Turbocharger overboost or underboost",
      "Transmission fault (especially CVT or DCT)",
      "Severe misfire that could damage the catalytic converter",
      "Critical sensor failure (MAF, MAP, crank position)",
      "Electrical system fault (low system voltage)",
    ],
    can_drive: "Yes, but with reduced power — you may be limited to 30-45 mph. Drive directly to a safe location or a repair shop. Do not attempt highway driving or towing. Restarting the vehicle may temporarily clear the condition but it will return if the fault persists.",
    min_cost: 100, max_cost: 3000, icon: ICONS.reducedPower,
    related_obd_codes: ["P2101", "P2135", "P2138", "P0299", "P0234", "P0700"],
  },
  {
    slug: "service-vehicle",
    title: "Service Vehicle Soon",
    severity: "informational",
    meaning: "The vehicle's onboard maintenance minder has determined that scheduled maintenance is due — oil change, tire rotation, inspection, etc. This is different from a check engine light and is NOT indicating a fault. It's based on mileage and/or time since the last service.",
    causes: [
      "Scheduled oil change interval reached",
      "Scheduled maintenance interval reached",
      "Tire rotation due",
      "Brake fluid change interval reached",
      "Cabin air filter change due",
      "Vehicle inspection due (state requirement)",
    ],
    can_drive: "Yes — this is a maintenance reminder, not a fault. Schedule your service appointment. Most vehicles require a specific procedure to reset the light after service (e.g., hold trip odometer button while turning ignition on).",
    min_cost: 50, max_cost: 300, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "oil-change",
    title: "Oil Change Reminder",
    severity: "informational",
    meaning: "The oil life monitor indicates the engine oil has degraded and needs changing. Modern vehicles calculate oil life based on driving conditions — short trips and towing deplete oil life faster than highway driving.",
    causes: [
      "Oil life percentage has reached 0-15%",
      "Scheduled mileage interval reached",
      "Oil life monitor needs reset after previous service",
    ],
    can_drive: "Yes for a short period — but change oil soon. Extended driving on degraded oil increases engine wear and may void warranty coverage. Most vehicles allow 500-1000 miles after the light comes on before oil is critically degraded.",
    min_cost: 35, max_cost: 120, icon: ICONS.oilChange,
    related_obd_codes: [],
  },
  {
    slug: "washer-fluid",
    title: "Windshield Washer Fluid Low",
    severity: "informational",
    meaning: "The windshield washer fluid reservoir is low or empty. Running the washer pump without fluid can damage the pump motor over time.",
    causes: [
      "Washer fluid reservoir is empty or near empty",
      "Faulty fluid level sensor",
      "Frozen washer fluid (winter — use winter-rated fluid)",
    ],
    can_drive: "Yes — but refill washer fluid at your earliest convenience. In winter conditions where road salt spray is common, keep the reservoir full at all times. Use winter-rated fluid (rated to -20°F or lower) to prevent freezing.",
    min_cost: 3, max_cost: 10, icon: ICONS.washerFluid,
    related_obd_codes: [],
  },
  {
    slug: "door-ajar",
    title: "Door / Trunk / Hood Ajar",
    severity: "informational",
    meaning: "One or more doors, the trunk/hatch, or the hood is not fully latched. Driving with a door unlatched is a safety hazard — the door could open at speed.",
    causes: [
      "Door, trunk, or hood not fully closed",
      "Faulty door latch sensor or switch",
      "Wiring damage in door harness (common in high-mileage vehicles)",
      "Hood latch sensor corroded or misaligned",
    ],
    can_drive: "Check all doors, trunk, and hood. If all are closed and the light persists, a sensor is faulty — safe to drive but the interior lights may stay on, draining the battery. Lock the vehicle manually to prevent battery drain.",
    min_cost: 0, max_cost: 200, icon: ICONS.door,
    related_obd_codes: [],
  },
  {
    slug: "seat-belt",
    title: "Seat Belt Reminder",
    severity: "informational",
    meaning: "A seat belt is not fastened in an occupied seat. This light is often accompanied by an audible chime. In most US states, front-seat belt use is legally required.",
    causes: [
      "Seat belt not buckled (check all seats)",
      "Heavy object on passenger seat triggering occupancy sensor",
      "Faulty seat belt buckle sensor",
      "Faulty passenger occupancy sensor (seat mat)",
    ],
    can_drive: "Buckle all seat belts. If the light persists with belts buckled, the sensor is faulty — safe to drive but the airbag system may not deploy correctly for an unbelted occupant.",
    min_cost: 0, max_cost: 300, icon: ICONS.seatbelt,
    related_obd_codes: ["B0050", "B0052", "B0077", "B0078"],
  },
  {
    slug: "security",
    title: "Security / Immobilizer / Anti-Theft",
    severity: "caution",
    meaning: "The vehicle's immobilizer system does not recognize the key or there is a security system fault. This may prevent the engine from starting, or the light may come on while driving, indicating a system fault.",
    causes: [
      "Key fob battery is dead or very weak",
      "Transponder chip in key not recognized",
      "Faulty immobilizer antenna ring around ignition",
      "ECU/immobilizer synchronization lost",
      "Aftermarket alarm system interfering",
      "Body control module (BCM) fault",
    ],
    can_drive: "If the vehicle starts: yes, but address the issue soon — the vehicle may fail to restart. Try your spare key if available. If the vehicle won't start: turn ignition to ON for 10 minutes (some vehicles re-learn the key), or use a spare key.",
    min_cost: 50, max_cost: 1200, icon: ICONS.security,
    related_obd_codes: ["B2955", "B2960", "B3031", "U0100", "U0155"],
  },
  {
    slug: "low-fuel",
    title: "Low Fuel Level",
    severity: "caution",
    meaning: "Fuel level is critically low — typically 1-2 gallons remaining. Running out of fuel can damage the fuel pump (which uses fuel for cooling), especially on modern direct-injection engines.",
    causes: ["Fuel level below reserve — refuel immediately"],
    can_drive: "Refuel as soon as possible. Most vehicles have 30-50 miles of range remaining when the light comes on, but this varies. Do not rely on the 'miles to empty' display — it becomes inaccurate at low fuel levels. Running a diesel completely empty requires fuel system priming.",
    min_cost: 30, max_cost: 150, icon: ICONS.fuel,
    related_obd_codes: [],
  },
  {
    slug: "cruise-control",
    title: "Cruise Control / Adaptive Cruise Control",
    severity: "informational",
    meaning: "Cruise control is active (green/white light) or there is a fault in the cruise control system (amber/yellow light). Adaptive cruise control may also be unavailable if the radar sensor is blocked by snow, ice, or mud.",
    causes: [
      "Switch or button fault on steering wheel",
      "Brake light switch fault (cruise disengages when brakes are applied)",
      "Clutch switch fault (manual transmission)",
      "Radar sensor blocked or misaligned (adaptive cruise)",
      "Vehicle speed sensor fault",
      "ABS/traction control fault affecting cruise operation",
    ],
    can_drive: "Yes — cruise control is a convenience feature. The vehicle drives normally without it. Check if radar sensor (usually behind front grille or windshield) is clean and unobstructed for adaptive cruise.",
    min_cost: 50, max_cost: 800, icon: ICONS.reducedPower,
    related_obd_codes: ["P0500", "P0503", "P0571", "P0572", "P0573"],
  },
  {
    slug: "lane-departure",
    title: "Lane Departure Warning (LDW) / Lane Keep Assist",
    severity: "informational",
    meaning: "The lane departure warning or lane keep assist system is active (green) or has a fault (amber). This system uses a forward-facing camera (usually behind the windshield) to detect lane markings.",
    causes: [
      "Windshield camera area dirty, fogged, or iced over",
      "Windshield replacement without camera recalibration",
      "Heavy rain, snow, or fog obscuring lane markings",
      "Faded or missing lane markings on road",
      "Camera module fault",
      "System turned off (check vehicle settings)",
    ],
    can_drive: "Yes — the vehicle drives normally without this system. It's a driver assistance feature only. Clean the windshield in front of the rearview mirror area.",
    min_cost: 100, max_cost: 1200, icon: ICONS.traction,
    related_obd_codes: ["C1001", "C1A00", "U0232", "U0235"],
  },
  {
    slug: "auto-high-beam",
    title: "Automatic High Beam",
    severity: "informational",
    meaning: "The automatic high beam system is active (green with 'A' symbol) or has a fault (amber). This system automatically switches between high and low beams based on oncoming traffic and ambient lighting.",
    causes: [
      "Windshield camera or sensor blocked (dirt, snow, fog)",
      "Headlight sensor fault",
      "System manually overridden or turned off",
      "Camera calibration lost after windshield replacement",
    ],
    can_drive: "Yes — manually control high beams using the traditional stalk control. This is a convenience feature only.",
    min_cost: 50, max_cost: 500, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "parking-brake",
    title: "Electric Parking Brake (EPB)",
    severity: "caution",
    meaning: "The electric parking brake has a fault or needs service. The parking brake may not engage or disengage properly. In some vehicles, a flashing EPB light indicates the parking brake is in service/maintenance mode for brake pad replacement.",
    causes: [
      "Parking brake not fully engaged or disengaged",
      "EPB actuator motor fault",
      "Rear brake pads worn below minimum (EPB needs service mode for replacement)",
      "EPB control module fault",
      "Low battery voltage affecting EPB operation",
      "Parking brake cable seized (older hybrid systems)",
    ],
    can_drive: "If the parking brake is fully released and the vehicle moves freely: yes, but have it checked soon. If the parking brake won't release or the vehicle feels held back: do not drive — towing with a partially engaged parking brake will destroy the rear brakes.",
    min_cost: 100, max_cost: 1200, icon: ICONS.brake,
    related_obd_codes: ["C1034", "C1035", "C1781", "C1782"],
  },
  {
    slug: "ev-system",
    title: "Electric Vehicle System Warning (EV/Hybrid)",
    severity: "critical",
    meaning: "The high-voltage electric drive system has a fault. This can affect the traction battery, electric motor, power electronics, or charging system. The vehicle may have reduced power, may not charge, or may not start.",
    causes: [
      "High-voltage battery fault (cell imbalance, degradation)",
      "Power inverter/DC-DC converter fault",
      "Electric motor or drive unit fault",
      "Charging system fault (onboard charger, charging port)",
      "Battery thermal management system fault",
      "12V auxiliary battery low (EVs still use a 12V battery for electronics)",
    ],
    can_drive: "If the vehicle starts: drive directly to a dealer or EV specialist. If the vehicle will not start or displays a 'Stop Safely' message: pull over and call for a tow. High-voltage system repairs must be performed by qualified technicians — do not attempt DIY on the HV system (lethal voltages, 400V-800V).",
    min_cost: 200, max_cost: 15000, icon: ICONS.ev,
    related_obd_codes: ["P0A01", "P0A04", "P0A08", "P0A0D", "P0A1A", "P1A00"],
  },
  {
    slug: "dpf",
    title: "Diesel Particulate Filter (DPF) Warning",
    severity: "caution",
    meaning: "The diesel particulate filter is becoming clogged with soot and needs regeneration. If ignored, the DPF can become irreversibly blocked, requiring expensive replacement. This light primarily affects modern diesel vehicles (2009+).",
    causes: [
      "Frequent short trips preventing automatic DPF regeneration",
      "Interrupted regeneration cycles (turning engine off mid-cycle)",
      "Faulty EGR system increasing soot production",
      "Faulty DPF pressure sensor",
      "Wrong engine oil (must use low-SAPS oil for DPF-equipped diesels)",
      "Turbocharger leaking oil into exhaust",
    ],
    can_drive: "Yes — but perform a forced regeneration as soon as possible: drive at highway speeds (55+ mph) for 20-30 minutes at 2,500+ RPM. Avoid short trips until the light clears. If the light begins flashing or turns red, the DPF is critically blocked — do not continue driving; have it professionally cleaned.",
    min_cost: 100, max_cost: 3500, icon: ICONS.dpf,
    related_obd_codes: ["P2002", "P244A", "P2452", "P2453", "P2454", "P2459"],
  },
  {
    slug: "adblue",
    title: "AdBlue / Diesel Exhaust Fluid (DEF) Warning",
    severity: "caution",
    meaning: "The diesel exhaust fluid (AdBlue/DEF) is low. This is used in Selective Catalytic Reduction (SCR) systems to reduce NOx emissions. Running completely out may prevent the engine from starting (anti-tamper regulation).",
    causes: [
      "DEF/AdBlue tank needs refilling",
      "Faulty DEF level sensor",
      "DEF quality issue (contaminated or incorrect fluid)",
      "SCR catalyst fault",
    ],
    can_drive: "Yes — but refill the DEF tank at your earliest convenience. Most vehicles have multiple warning stages: first warning (refill soon), second warning (refill now), third warning (engine will not restart after shutdown). Do not put diesel fuel in the DEF tank.",
    min_cost: 10, max_cost: 50, icon: ICONS.adBlue,
    related_obd_codes: ["P203F", "P204F", "P20E8", "P20E9", "P249C"],
  },
  {
    slug: "fuel-filter-water",
    title: "Fuel Filter Water (Diesel)",
    severity: "caution",
    meaning: "Water has accumulated in the diesel fuel filter/water separator and needs to be drained. Water in diesel fuel can cause injector damage, fuel pump failure, and microbial growth in the fuel tank.",
    causes: [
      "Condensation in fuel tank (common in humid climates)",
      "Contaminated fuel from a gas station",
      "Fuel filter water separator full (needs draining)",
      "Water-in-fuel sensor fault",
    ],
    can_drive: "Yes short-term — but drain the water separator as soon as possible. Water in diesel fuel causes catastrophic injector and pump damage if not addressed. Most diesel vehicles have a drain valve on the fuel filter housing that can be operated without tools. If the light returns quickly after draining, the fuel tank may need flushing.",
    min_cost: 0, max_cost: 500, icon: ICONS.fuel,
    related_obd_codes: ["P2265", "P2266", "P2267", "P2269"],
  },
  {
    slug: "transmission-temp",
    title: "Transmission Temperature Warning",
    severity: "critical",
    meaning: "Transmission fluid temperature has exceeded safe operating range. Overheated transmission fluid loses its lubricating properties and can cause permanent damage to clutches, bands, and seals. This is most common when towing heavy loads or in stop-and-go traffic in hot weather.",
    causes: [
      "Towing beyond vehicle's rated capacity",
      "Low transmission fluid level",
      "Old or degraded transmission fluid",
      "Transmission cooler restricted or blocked",
      "Torque converter failing (generating excess heat)",
      "Slipping transmission (internal wear)",
    ],
    can_drive: "Pull over safely, place in Park or Neutral, and let the engine idle for 10-15 minutes to circulate fluid through the cooler. Do NOT shut off the engine immediately — idling in Park cools the transmission faster. If the light comes on frequently, have the transmission serviced. Consider installing an auxiliary transmission cooler for towing.",
    min_cost: 100, max_cost: 4000, icon: ICONS.coolantTemp,
    related_obd_codes: ["P0711", "P0712", "P0713", "P0715", "P0716", "P0717"],
  },
  {
    slug: "awd",
    title: "AWD / 4WD System Warning",
    severity: "caution",
    meaning: "The all-wheel drive or four-wheel drive system has a fault. The vehicle may default to front-wheel drive (or rear-wheel drive) only. The system may have disabled itself to protect the drivetrain.",
    causes: [
      "Tire size mismatch between front and rear axles (most common — check tire pressures and sizes)",
      "Transfer case actuator motor fault",
      "Low transfer case or differential fluid",
      "AWD coupling or Haldex clutch fault",
      "Wheel speed sensor fault (shared with ABS)",
      "Transfer case control module fault",
    ],
    can_drive: "Yes — the vehicle will operate in two-wheel-drive mode. Avoid off-road driving or conditions requiring AWD. The most common cause is tire size/pressure difference — check all tires match and inflate to spec.",
    min_cost: 100, max_cost: 3000, icon: ICONS.traction,
    related_obd_codes: ["C0371", "C0374", "C0379", "C0380", "C1240", "C1241"],
  },
  {
    slug: "air-suspension",
    title: "Air Suspension / Ride Height Warning",
    severity: "caution",
    meaning: "The air suspension system has a fault. The vehicle may sit unevenly, ride harshly, or be unable to maintain proper ride height. This primarily affects luxury SUVs (Range Rover, Mercedes, Audi) and trucks with air-ride systems.",
    causes: [
      "Air spring/air bag leak (most common — rubber degrades over time)",
      "Air compressor failure (worn out from constant cycling)",
      "Ride height sensor fault or misalignment",
      "Air line leak (check for hissing sounds)",
      "Valve block fault (moisture contamination)",
      "Relay or fuse failure",
    ],
    can_drive: "If the vehicle maintains normal ride height: yes, but have it checked soon. If the vehicle drops to the bump stops (very low, harsh ride): tow to a shop — driving on deflated air springs will damage the air bags and potentially the suspension components.",
    min_cost: 300, max_cost: 3000, icon: ICONS.service,
    related_obd_codes: ["C1525", "C1526", "C1530", "C1531", "C1550", "C1551"],
  },
  {
    slug: "exterior-light",
    title: "Exterior Light Failure",
    severity: "caution",
    meaning: "One or more exterior lights is not functioning — headlight, brake light, turn signal, or running light. This is both a safety hazard and a traffic violation in all US states.",
    causes: [
      "Burnt-out bulb (most common)",
      "Corroded bulb socket or connector",
      "Blown fuse for light circuit",
      "Faulty headlight ballast (HID/LED headlights)",
      "Body control module (BCM) fault for lighting circuit",
    ],
    can_drive: "Only in daylight. Replace the bulb before driving at night. Most auto parts stores will install bulbs for free with purchase. Check all lights (headlights, brake lights, turn signals) before driving in darkness.",
    min_cost: 5, max_cost: 500, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "blind-spot",
    title: "Blind Spot Monitor / Rear Cross Traffic Alert",
    severity: "informational",
    meaning: "The blind spot monitoring or rear cross traffic alert system is temporarily unavailable or has a fault. These systems use radar sensors (usually behind the rear bumper) to detect vehicles in adjacent lanes.",
    causes: [
      "Radar sensors blocked by mud, snow, or ice (clean bumper corners)",
      "Heavy rain or snow interfering with radar signal",
      "Trailer attached (many vehicles disable BSM when towing)",
      "Radar sensor misaligned or faulty",
      "System turned off (check vehicle settings)",
    ],
    can_drive: "Yes — use mirrors and shoulder checks for lane changes. This is a driver assistance feature only.",
    min_cost: 100, max_cost: 1500, icon: ICONS.security,
    related_obd_codes: ["U0232", "U0235", "B11D8", "B11D9"],
  },
  {
    slug: "start-stop",
    title: "Auto Start-Stop / Mild Hybrid Warning",
    severity: "informational",
    meaning: "The auto start-stop system or mild-hybrid system has a fault or has been temporarily disabled. This system automatically shuts off the engine when stopped and restarts when the brake is released to save fuel.",
    causes: [
      "12V auxiliary battery degraded (start-stop vehicles use AGM or EFB batteries — need replacement)",
      "Hood not fully closed (safety interlock for start-stop)",
      "Engine not at operating temperature (normal — system re-enables when warm)",
      "Cabin climate demand too high (normal in extreme weather)",
      "Auxiliary battery or DC-DC converter fault (mild hybrid)",
    ],
    can_drive: "Yes — the vehicle operates normally, just without automatic engine stop/start. The most common cause is an aging 12V battery that no longer meets the start-stop spec. Replace with an OEM-spec AGM battery.",
    min_cost: 150, max_cost: 500, icon: ICONS.battery,
    related_obd_codes: ["P0615", "P0616", "P0617", "P06EF", "P06F0"],
  },
  {
    slug: "suspension",
    title: "Adaptive / Electronic Suspension Warning",
    severity: "caution",
    meaning: "The adaptive damping or electronic suspension control system has a fault. The vehicle may default to a firm ride and lose the ability to switch between comfort/sport modes. This affects vehicles with magnetic ride, air suspension without ride height issues, or electronically controlled dampers.",
    causes: [
      "Damper solenoid or actuator fault",
      "Suspension accelerometer or position sensor fault",
      "Control module communication error",
      "Wiring damage at damper connector",
      "Aftermarket springs/dampers without electronic compatibility",
    ],
    can_drive: "Yes — the suspension defaults to a safe (firm) damping mode. Ride quality may be harsher than normal. The vehicle handles safely. Have the system diagnosed at your convenience.",
    min_cost: 200, max_cost: 2000, icon: ICONS.powerSteering,
    related_obd_codes: ["C0570", "C0575", "C0580", "C0585", "C0590"],
  },
  {
    slug: "key-fob",
    title: "Key Fob Battery Low / Key Not Detected",
    severity: "informational",
    meaning: "The vehicle is having difficulty detecting the key fob. The fob battery may be low, or there may be signal interference. On keyless start vehicles, this may prevent push-button starting.",
    causes: [
      "Key fob battery low (CR2032 or similar — $2 replacement)",
      "Signal interference from other electronics or radio towers",
      "Key fob stored too far from the vehicle",
      "Key fob internal damage (water exposure, physical damage)",
      "Vehicle receiver antenna fault (rare)",
    ],
    can_drive: "Most vehicles have a backup starting procedure: hold the key fob directly against the start button (the button contains an NFC coil that reads the fob even with a dead battery) and press. Check your owner's manual for the exact procedure for your vehicle.",
    min_cost: 2, max_cost: 300, icon: ICONS.security,
    related_obd_codes: [],
  },
  {
    slug: "emissions",
    title: "Emissions System Warning",
    severity: "caution",
    meaning: "The vehicle's emissions control system has a fault. This is common on diesel vehicles and some newer gasoline vehicles with enhanced emissions monitoring. In states with emissions testing, this light will cause a failed inspection.",
    causes: [
      "SCR/AdBlue system fault (diesel)",
      "DPF regeneration overdue (diesel)",
      "EGR system fault",
      "EVAP system leak (gasoline)",
      "Secondary air injection fault",
      "NOx sensor fault (diesel)",
    ],
    can_drive: "Yes — the vehicle is safe to drive but will produce higher emissions. Address before your next emissions inspection. Diesel vehicles with SCR faults may eventually enter a 'no restart' mode if warnings are repeatedly ignored.",
    min_cost: 100, max_cost: 2500, icon: ICONS.checkEngine,
    related_obd_codes: ["P0401", "P0402", "P0442", "P0455", "P2002", "P244A"],
  },
  {
    slug: "hood-open",
    title: "Hood Open Warning",
    severity: "critical",
    meaning: "The hood is not fully latched. Driving with an unlatched hood can result in the hood flying open at speed, completely blocking forward visibility — an extremely dangerous situation.",
    causes: [
      "Hood not fully closed after maintenance or fluid check",
      "Hood latch sensor misaligned or faulty",
      "Secondary hood latch stuck (lubricate latch mechanism)",
    ],
    can_drive: "Stop immediately and close the hood fully. Push down firmly on both front corners of the hood until you hear two clicks. If the light persists with the hood latched, the sensor is faulty — safe to drive but verify the hood is physically secure before driving.",
    min_cost: 0, max_cost: 150, icon: ICONS.door,
    related_obd_codes: [],
  },
  {
    slug: "esp-off",
    title: "Electronic Stability Program (ESP) Off",
    severity: "informational",
    meaning: "The electronic stability program has been manually turned off via the ESP button, or is temporarily disabled due to a fault. ESP helps prevent skidding and loss of control by applying individual brakes and reducing engine power.",
    causes: [
      "ESP button pressed (check for ESP OFF or similar button, often near the shifter)",
      "System disabled for diagnostic purposes",
      "ABS/traction control fault causing ESP to default off",
      "Steering angle sensor needs recalibration after alignment",
    ],
    can_drive: "If manually turned off: press the ESP button to re-enable. If re-enabling fails: drive cautiously, especially on wet or curved roads. ESP is a safety net — drive as if it's not there. Have the system checked if it won't re-enable.",
    min_cost: 0, max_cost: 800, icon: ICONS.esc,
    related_obd_codes: ["C0040", "C0050", "C1233", "C1288"],
  },
  {
    slug: "airbag-off",
    title: "Passenger Airbag Off",
    severity: "informational",
    meaning: "The front passenger airbag has been automatically disabled because the seat occupancy sensor detects no passenger, or a small child/child seat. This is NORMAL behavior. The light should turn off when an adult sits in the passenger seat.",
    causes: [
      "No passenger in seat (normal)",
      "Small child or child seat in front passenger seat (normal — airbag disabled for safety)",
      "Heavy bag or object on passenger seat (may trigger sensor)",
      "Faulty seat occupancy sensor mat (if light stays on with an adult seated)",
    ],
    can_drive: "Yes. This is a normal function. If the light stays off when an adult is seated in the passenger seat, the airbag is active. If the light stays ON with an adult passenger, have the occupancy sensor checked — the airbag will not deploy for that passenger in a collision.",
    min_cost: 0, max_cost: 800, icon: ICONS.airbag,
    related_obd_codes: ["B0077", "B0078", "B0090", "B0091"],
  },
  {
    slug: "rear-spoiler",
    title: "Active Rear Spoiler / Aerodynamic System",
    severity: "caution",
    meaning: "The active rear spoiler or aerodynamic system has a fault. The spoiler may not deploy at speed, affecting high-speed stability. This primarily affects sports cars with active aero (e.g., Porsche, Audi TT, Bugatti).",
    causes: [
      "Spoiler mechanism jammed or obstructed",
      "Spoiler motor or actuator fault",
      "Control module fault",
      "Fuse blown for spoiler circuit",
    ],
    can_drive: "Yes at normal speeds. Avoid high-speed driving if your vehicle relies on active aero for stability. Most vehicles default the spoiler to a safe (deployed or retracted) position when a fault is detected.",
    min_cost: 300, max_cost: 3000, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "night-vision",
    title: "Night Vision System",
    severity: "informational",
    meaning: "The night vision or thermal imaging system is unavailable or has a fault. This is a luxury vehicle feature (BMW, Mercedes, Audi, Cadillac) that uses an infrared camera to detect pedestrians and animals beyond headlight range.",
    causes: [
      "Infrared camera lens dirty, fogged, or iced over",
      "Camera calibration lost",
      "System temporarily unavailable in extreme ambient temperatures",
      "Camera or control module fault",
      "Windshield replacement without camera recalibration",
    ],
    can_drive: "Yes — this is an assistance feature only. Drive normally using headlights and visual observation.",
    min_cost: 200, max_cost: 3000, icon: ICONS.security,
    related_obd_codes: [],
  },
  {
    slug: "trailer",
    title: "Trailer Connection / Trailer Light Fault",
    severity: "caution",
    meaning: "The vehicle has detected a trailer electrical connection, or there is a fault with the trailer lighting circuit. A faulty trailer light is both a safety hazard and a traffic violation.",
    causes: [
      "Trailer connected (normal — some vehicles show this light when a trailer is detected)",
      "Trailer light bulb burnt out",
      "Trailer wiring harness corrosion or damage",
      "Trailer connector pins corroded or bent",
      "Blown fuse for trailer lighting circuit",
    ],
    can_drive: "If towing: check all trailer lights (running lights, brake lights, turn signals). If lights are working, the fault may be intermittent — clean the connector with electrical contact cleaner. If not towing and the light is on, there may be a short in the trailer wiring connector.",
    min_cost: 0, max_cost: 200, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "brake-pad-wear",
    title: "Brake Pad Wear Indicator",
    severity: "caution",
    meaning: "The brake pads have worn to their minimum thickness and need replacement. Most modern vehicles have electronic wear sensors embedded in the pads. Continuing to drive with worn pads will damage the brake rotors, turning a $200 pad job into a $500+ pad-and-rotor job.",
    causes: [
      "Brake pads worn to minimum thickness (2-3mm remaining)",
      "Brake pad wear sensor wire broken or disconnected",
      "Uneven pad wear (caliper slide pins seized)",
    ],
    can_drive: "Schedule pad replacement within 1-2 weeks. You have some remaining friction material — the wear sensor triggers before the pads are metal-to-metal. Listen for grinding: if you hear metal-on-metal scraping, the pads are gone and the rotors are being damaged. Replace pads AND rotors at that point.",
    min_cost: 150, max_cost: 500, icon: ICONS.brake,
    related_obd_codes: ["C1266", "C1267"],
  },
  {
    slug: "hill-descent",
    title: "Hill Descent Control",
    severity: "informational",
    meaning: "Hill descent control is active (green light — vehicle is automatically controlling speed on a steep descent) or the system has a fault (amber light). This system is common on trucks and SUVs and uses ABS to maintain a constant low speed downhill.",
    causes: [
      "System manually turned on (green light — normal, press button to deactivate)",
      "System unavailable due to high vehicle speed (only works below ~20 mph)",
      "ABS/traction control fault affecting hill descent",
      "Hill descent switch or module fault",
    ],
    can_drive: "Yes. Use manual braking on descents if the system is not available. The vehicle's normal brakes are unaffected.",
    min_cost: 50, max_cost: 500, icon: ICONS.traction,
    related_obd_codes: [],
  },
  {
    slug: "headlight-leveling",
    title: "Headlight Leveling / Adaptive Headlight",
    severity: "caution",
    meaning: "The automatic headlight leveling system or adaptive (swiveling) headlight system has a fault. Headlights may be aimed too high (blinding oncoming traffic) or too low (reduced visibility). Adaptive headlights may not swivel with steering input.",
    causes: [
      "Headlight level sensor broken or disconnected (attached to suspension arm)",
      "Headlight leveling motor failed (inside headlight housing)",
      "Adaptive headlight module fault",
      "Aftermarket suspension changes affecting sensor position",
      "Headlight assembly replaced without calibration",
    ],
    can_drive: "Yes — but be aware headlights may not be optimally aimed. Avoid blinding oncoming traffic. Have the system checked at your next service. Some vehicles allow manual headlight adjustment via a dial on the dashboard.",
    min_cost: 100, max_cost: 1500, icon: ICONS.service,
    related_obd_codes: [],
  },
  {
    slug: "forward-collision",
    title: "Forward Collision Warning / Automatic Emergency Braking",
    severity: "caution",
    meaning: "The forward collision warning or automatic emergency braking system is temporarily unavailable or has a fault. The vehicle will not provide collision warnings or automatic braking while this system is offline.",
    causes: [
      "Windshield camera or front radar blocked by snow, ice, mud, or heavy rain",
      "Front radar sensor misaligned (typically behind front grille or bumper)",
      "Windshield replacement without camera recalibration",
      "Extreme temperatures (system temporarily disabled)",
      "System turned off in vehicle settings",
      "Camera or radar module fault",
    ],
    can_drive: "Yes — but drive with increased attention to the road ahead. This is a driver assistance feature only. Clean the windshield and front grille area. If the light persists, have the system scanned.",
    min_cost: 100, max_cost: 2500, icon: ICONS.reducedPower,
    related_obd_codes: ["C1001", "C1A00", "B14D9", "C1A67"],
  },
  {
    slug: "electric-parking",
    title: "Electric Parking Brake Service Mode",
    severity: "informational",
    meaning: "The electric parking brake is in service/maintenance mode. This mode must be activated before performing rear brake pad replacement, as the EPB actuator must be electronically retracted. Attempting to compress the caliper pistons without activating service mode will damage the EPB actuator.",
    causes: [
      "Service mode manually activated for brake pad replacement",
      "EPB system fault (accompanied by additional warnings)",
    ],
    can_drive: "If you did not intentionally activate service mode: take the vehicle to a shop immediately — the parking brake may not function. If you entered service mode for brake work: exit service mode after completing the job using the same procedure (varies by vehicle — consult service manual).",
    min_cost: 0, max_cost: 300, icon: ICONS.brake,
    related_obd_codes: [],
  },
  {
    slug: "regenerative-braking",
    title: "Regenerative Braking System (EV/Hybrid)",
    severity: "caution",
    meaning: "The regenerative braking system is reduced or unavailable. The vehicle may rely more heavily on friction brakes, reducing energy recovery and range. Brake pedal feel may change — this is normal and the friction brakes still work.",
    causes: [
      "High-voltage battery is fully charged (no capacity for regen — normal, no action needed)",
      "Battery temperature too low or too high (regen limited to protect battery)",
      "Brake system fault affecting regen coordination",
      "Drive mode selection (some modes reduce regen — check settings)",
    ],
    can_drive: "Yes. Friction brakes provide full stopping power. Expect reduced one-pedal driving effect and slightly reduced range. This is often temporary and resolves when the battery discharges slightly or reaches optimal temperature.",
    min_cost: 0, max_cost: 2000, icon: ICONS.ev,
    related_obd_codes: ["P0A7A", "P0A7D", "P1A00", "P0A80"],
  },
  {
    slug: "catalytic-converter",
    title: "Catalytic Converter / Emissions System",
    severity: "caution",
    meaning: "The catalytic converter or downstream emissions system has a fault. This may indicate a failing catalytic converter, which is one of the most expensive emissions repairs and often a symptom of an underlying engine issue (misfire, oil burning, rich fuel mixture) that damaged the converter.",
    causes: [
      "Engine misfire dumping unburned fuel into the exhaust (most common cause of cat failure)",
      "Burning oil (worn piston rings, valve seals) contaminating the converter",
      "Rich fuel mixture (faulty O2 sensor, MAF, or fuel injector)",
      "Physical damage to converter (impact with road debris)",
      "Normal aging (converters last 100K-150K miles under normal conditions)",
    ],
    can_drive: "Yes short-term — but address promptly. A failing catalytic converter will eventually clog, causing loss of power, stalling, and potentially engine damage from excessive backpressure. Also: fix the ROOT CAUSE (misfire, oil burning) before replacing the converter, or the new one will fail too.",
    min_cost: 500, max_cost: 3000, icon: ICONS.checkEngine,
    related_obd_codes: ["P0420", "P0430", "P0421", "P0431", "P2096", "P2098"],
  },
  {
    slug: "timing-belt",
    title: "Timing Belt Replacement Due",
    severity: "critical",
    meaning: "The timing belt replacement interval has been reached. This is a critical maintenance item — if the timing belt breaks while driving, the engine will suffer catastrophic damage (pistons hitting valves) on interference engines. Most vehicles require timing belt replacement every 60,000-105,000 miles.",
    causes: [
      "Scheduled maintenance interval reached (check owner's manual for your vehicle's interval)",
      "Timing belt tensioner failing (noise from belt area)",
    ],
    can_drive: "No — schedule replacement immediately. If you hear a slapping or rattling noise from the timing cover area, the belt tensioner is failing and the belt could snap at any moment. Tow to a shop if noise is present. Replace the water pump at the same time (driven by the timing belt on most engines).",
    min_cost: 500, max_cost: 1500, icon: ICONS.generic,
    related_obd_codes: ["P0016", "P0017", "P0018", "P0019", "P0340", "P0341"],
  },
];

export function getWarningLightBySlug(slug: string): WarningLight | undefined {
  return warningLights.find((w) => w.slug === slug);
}

export function getWarningLightsBySeverity(severity: WarningLightSeverity): WarningLight[] {
  return warningLights.filter((w) => w.severity === severity);
}
